#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Environment variables for GUI stuff
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
#export GTK_IM_MODULE=xim
export GDK_USE_XFT=1
export XMODIFIERS="@im=none"
export QT_QPA_PLATFORMTHEME=gtk2

# Run in background
~/.dots/bin/set-monitor
xset +fp /usr/share/fonts/local
xsetroot -solid '#586e75' -cursor_name left_ptr -name "$(date +"%F %R")" &
feh --bg-fill ~/.extra/wallpaper.jpg &
# /usr/bin/urxvtd -q -o -f
# sleep 2 && urxvtc -geometry 35x9 -e tty-clock -b -c -C 3 -D &
xset r rate 200 100 &
ksuperkey &
unclutter &
udiskie -aNtq2 &
pulseaudio --start &
xcalib -d :0 ~/.extra/mbp11x/colorprofile.icc &
compton -b --config ~/.config/compton.conf
# dropbox &
thunar --daemon &
greenclip daemon &
# conky -d &
transmission-daemon &

# Start desktop environment
# exec i3 >> ~/.config/i3/.i3log 2>&1
exec i3
