#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Environment variables for GUI stuff
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
#export GTK_IM_MODULE=xim
export GDK_USE_XFT=1
export XMODIFIERS="@im=none"
export QT_QPA_PLATFORMTHEME=gtk2

# Run in background
xset +fp /usr/share/fonts/local
xsetroot -solid black -cursor_name left_ptr -name "$(date +"%F %R")" &
xset r rate 200 100 &
udiskie -aNtq2 &
pulseaudio --start & 
thunar --daemon & 
dropbox & 
transmission-daemon & 
~/.extra/mbp11x/screenlayout/default.sh &
xcalib -d :0 ~/.extra/mbp11x/colorprofile.icc &
feh --bg-fill ~/.extra/wallpaper.jpg &
urxvtd -q -o -f

# Start desktop environment
exec i3
